name: Build project

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew projectCodestyle

      - run: ./gradlew assemble

      - run: ./gradlew projectCoverage

      - run: ./gradlew projectLint

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: lint-results
          path: '${{ github.workspace }}/**/build/**/reports/lint-results-*.html'

  ui-test:
    runs-on: macos-latest
    strategy:
      matrix:
        apiVersion: [ 23, 28, 30, 31, 32 ]
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          target: google_apis
          arch: x86_64
          disable-spellchecker: true
          script: ./gradlew connectedCheck

      - name: Upload tests result
        uses: actions/upload-artifact@v3
        with:
          name: "test-results [${{ matrix.apiVersion }}]"
          path: "${{ github.workspace }}/**/reports/**"
