name: TZDB check

on:
  push:
  schedule:
    - cron: '0 3 * * 1,4'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - id: current-tzdb-version
        run: |
          echo '::set-output name=tzdb_version::$(grep "ianaVersion" "tzdb_version.properties" | cut -d'=' -f2)'

      - id: latest-tzdb-version
        run: |
          wget -q https://data.iana.org/time-zones/tzdata-latest.tar.gz
          tar -xf tzdata-latest.tar.gz version
          echo '::set-output name=tzdb_version::$(cat version)'

      - run: echo "The latest versions is ${{ steps.latest-tzdb-version.outputs.tzdb_version }}"

      - run: echo "Current version is ${{ steps.current-tzdb-version.outputs.tzdb_version }}"

      - if: ${{ steps.current-tzdb-version.outputs.tzdb_version == steps.latest-tzdb-version.outputs.tzdb_version }}
        run: echo "COmparison works"
